# Don't double-build PR commits. See: http://stackoverflow.com/a/31882307/1877326
branches:
  only: 
    - master
dist: xenial
sudo: required
language: python
python:
  - "3.8"
services:
  - postgresql
  - redis-server
addons:
  postgresql: "9.5"
  chrome: stable
  apt:
    packages:
      - build-essential
      - fontforge
      - gettext
      - git-core
      - libpcre3
      - libpcre3-dev
      - libpq-dev
cache:
  directories:
    - $HOME/.pip-download-cache
    - node_modules
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - npm run copy-fonts
  - npm run build
  - pytest -vv --cov
  - npm run test
after_script:
  - coverage xml && python-codacy-coverage -r coverage.xml
  - coveralls
env:
  # All about YAML line breaks: https://stackoverflow.com/a/21699210
  - >-
       PIP_DOWNLOAD_CACHE=$HOME/.pip-download-cache
       DJANGO_DEBUG=False
       DJANGO_SECRET_KEY=ZGtvYm90cmF2aXM
       DJANGO_SETTINGS_MODULE=kobo.settings.testing
       DJANGO_LANGUAGE_CODES="en ar es fr hi ku pl pt zh-hans"
       DATABASE_URL="postgres://postgres@localhost:5432/travis_ci_test"
       REDIS_SESSION_URL="redis://localhost:6379"
       TRAVIS_NODE_VERSION="8"
       PATH=$PATH:$HOME/build/kobotoolbox/kpi/node_modules/.bin/
install:
  -  >-
        rm -rf ~/.nvm &&
        git clone https://github.com/creationix/nvm.git ~/.nvm &&
        (cd ~/.nvm &&
        git checkout `git describe --abbrev=0 --tags`) &&
        source ~/.nvm/nvm.sh &&
        nvm install $TRAVIS_NODE_VERSION
  - npm install -g install npm@latest
  - npm config set strict-ssl false && npm install --save-dev
  - pip install --upgrade 'pip>=8.0' wheel
  - pip install pip-tools
  - pip-sync dependencies/pip/travis_ci.txt
  - >-
        git submodule init &&
        git submodule update --remote &&
        python manage.py compilemessages
