# Generated by Django 2.2.7 on 2020-09-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0007_alter_jsonfield_to_jsonbfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationfile',
            name='content',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='configurationfile',
            name='slug',
            field=models.CharField(choices=[('logo', 'logo'), ('logo_small', 'logo_small'), ('login_background', 'login_background')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='perusersetting',
            name='name',
            field=models.CharField(default='INTERCOM_APP_ID', max_length=255, unique=True),
        ),
    ]
